//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hazlo.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class base_team_player_map
    {
        public int base_team_player_map_id { get; set; }
        public int base_team_id { get; set; }
        public int base_player_id { get; set; }
        public System.DateTime created_on { get; set; }
        public System.DateTime updated_on { get; set; }
        public string created_by { get; set; }
        public string updated_by { get; set; }
    }
}
